# 配置文件有效性
status : 1

# 回测配置
begin_date : '2016-01-01'
end_date : '2022-12-31'

# 加密信息
tushare_token : '/home/winston/tushare_project/tokens/tushare'
#tushare_token : '/Users/winston/api_mine/config/tokens/tushare'

# 本地地址（尽量少指定）
api_path : '/home/winston/tushare_project/sys23'
# api_path : '/Users/winston/mygitrep/sys23/'


# 相对地址
path :
    tradedates : '{}/tradedates.csv'
    cache : '{}/cache/'
    factors_csv : '{}/cache/factors_csv/'
    factors_res : '{}/cache/factors_res/'
    demo : '{}/demo/'
    cache_demo : '{}/demo/cache_demo/'
    new_share : '{}/cache/new_share.csv'  # Xd
    suspend_d : '{}/cache/suspend_d.csv'  # R/S/RS/SR, 1d
    st_status : '{}/cache/st_status.csv'  # 1/0, 1d
    open : '{}/cache/open.csv'
    high : '{}/cache/high.csv'
    low : '{}/cache/low.csv'
    close : '{}/cache/close.csv'
    openAdj : '{}/cache/openAdj.csv'
    highAdj : '{}/cache/highAdj.csv'
    lowAdj : '{}/cache/lowAdj.csv'
    closeAdj : '{}/cache/closeAdj.csv'
    vol : '{}/cache/vol.csv'
    amount : '{}/cache/amount.csv'
    up_limit : '{}/cache/up_limit.csv'
    down_limit : '{}/cache/down_limit.csv'
    updown_status : '{}/cache/updown_status.csv'  # OU/OD/CU/CD, 1d
    turnover_rate : '{}/cache/turnover_rate.csv'
    turnover_rate_f : '{}/cache/turnover_rate_f.csv'
    volume_ratio : '{}/cache/volume_ratio.csv'
    pe : '{}/cache/pe.csv'
    pe_ttm : '{}/cache/pe_ttm.csv'
    pb : '{}/cache/pb.csv'
    ps : '{}/cache/ps.csv'
    ps_ttm : '{}/cache/ps_ttm.csv'
    dv_ratio : '{}/cache/dv_ratio.csv'
    dv_ttm : '{}/cache/dv_ttm.csv'
    total_share : '{}/cache/total_share.csv'
    float_share : '{}/cache/float_share.csv'
    free_share : '{}/cache/free_share.csv'
    total_mv : '{}/cache/total_mv.csv'
    circ_mv : '{}/cache/circ_mv.csv'
    CSI300: '{}/cache/index_weight_CSI300.csv'
    CSI500: '{}/cache/index_weight_CSI500.csv'
    CSI800: '{}/cache/index_weight_CSI800.csv'
    CSI1000: '{}/cache/index_weight_CSI1000.csv'

# 市场环境
year_length : 246
csi_pool : 
    CSI300 : '399300.SZ'  # 沪深300指数由上海和深圳证券市场中市值大、流动性好的300只股票组成，综合反映中国A股市场上市股票价格的整体表现。
    CSI500 : '000905.SH'  # 中证500指数由全部A股中剔除沪深300指数成份股及总市值排名前300名的股票后，总市值排名靠前的500只股票组成，综合反映中国A股市场中一批中小市值公司的股票价格表现。
    CSI800 : '000906.SH'  # 中证800指数由中证500和沪深300指数成份股组成，综合反映中国A股市场大中小市值公司的股票价格表现。
    CSI1000 : '000852.SH'  # 中证1000指数由全部A股中剔除中证800指数成份股后，规模偏小且流动性好的1000只股票组成，综合反映中国A股市场中一批小市值公司的股票价格表现。
    
# 更新 path.cache_demo 下数据展示
update_cache_demo : 0
